=== metanomial/constitution/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="document">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="content">
					<xsd:sequence>
						<xsd:choice minOccurs="0" maxOccurs="unbounded">
							<xsd:element name="signatory" type="xsd:string"/>
							<xsd:element ref="party"/>
						</xsd:choice>
						<xsd:element ref="see-also" minOccurs="0"/>
						<xsd:element ref="copyright" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="lang" type="xsd:language"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="party">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="signatory" type="xsd:string" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:token" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="see-also">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="link" type="reference" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="copyright">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="paragraph" type="text"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="content">
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="paragraph" type="text"/>
			<xsd:element name="section" type="content"/>
			<xsd:element name="note" type="division"/>
		</xsd:choice>
		<xsd:attribute name="heading" type="xsd:token" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="division">
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="paragraph" type="text"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="text" mixed="true">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="strong" type="xsd:string"/>
			<xsd:element name="link" type="reference"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="reference">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="href" type="xsd:anyURI" use="required"/>
				<xsd:attribute name="lang" type="xsd:language"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:schema>

=== metanomial/constitution/mayflower-es.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="document.xsl"?>
<document
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="document.xsd"
	heading="Pacto del Mayflower"
	lang="es">
	<section>
		<paragraph><strong>En el nombre de Dios, Amén.</strong> Nosotros, cuyos nombres están escritos debajo, los sujetos leales de nuestro Temible Soberano Señor Rey Jaime, por la Gracia de Dios, de Gran Bretaña, Francia e Irlanda, Rey, Defensor de la Fe. Habiendo emprendido para la Gloria de Dios, y el Avance de la Fé Cristiana y el Honor de nuestro Rey y Patria, una travesía para plantar la primera colonia en las Partes Norteñas de Virginia; hacemos por estos presentes, solemne y mutuamente en la Presencia de Dios y unos con otros, pacto y nos combinamos juntos en un Cuerpo Político Civil para nuestro orden y preservación y fomento de los fines antedichos; y por virtud de esto establecemos y aprobamos, constituimos y formamos, tales justas e iguales leyes, Ordenanzas, Actas, Constituciones y Oficios, de tiempo en tiempo, según sea considerado muy propio y conveniente para el Bienestar General de la Colonia, a la cual prometemos toda la Obediencia y Sumisión debidas. <strong>En fe</strong> de lo cual hemos suscripto nuestros nombres a esto en Cape Cod el once de Noviembre, en el Reino de Nuestro Soberano Señor Rey Jaime de Inglaterra, Francia e Irlanda, el dieciocho y de Escocia, el cincuenta y cuatro. Anno Domini, 1620.</paragraph>
	</section>
	<signatory>John Carver</signatory>
	<signatory>William Bradford</signatory>
	<signatory>Edward Winslow</signatory>
	<signatory>William Brewster</signatory>
	<signatory>Isaac Allerton</signatory>
	<signatory>Capitán Myles Standish</signatory>
	<signatory>John Alden</signatory>
	<signatory>Samuel Fuller</signatory>
	<signatory>Christopher Martin</signatory>
	<signatory>William Mullins</signatory>
	<signatory>William White</signatory>
	<signatory>Richard Warren</signatory>
	<signatory>John Howland</signatory>
	<signatory>Stephen Hopkins</signatory>
	<signatory>Edward Tilley</signatory>
	<signatory>John Tilley</signatory>
	<signatory>Francis Cooke</signatory>
	<signatory>Thomas Rogers</signatory>
	<signatory>Thomas Tinker</signatory>
	<signatory>John Rigsdale</signatory>
	<signatory>Edward Fuller</signatory>
	<signatory>John Turner</signatory>
	<signatory>Francis Eaton</signatory>
	<signatory>James Chilton</signatory>
	<signatory>John Crackstone</signatory>
	<signatory>John Billington</signatory>
	<signatory>Moses Fletcher</signatory>
	<signatory>John Goodman</signatory>
	<signatory>Degory Priest</signatory>
	<signatory>Thomas Williams</signatory>
	<signatory>Gilbert Winslow</signatory>
	<signatory>Edmund Margeson</signatory>
	<signatory>Peter Browne</signatory>
	<signatory>Richard Britteridge</signatory>
	<signatory>George Soule</signatory>
	<signatory>Richard Clarke</signatory>
	<signatory>Richard Gardiner</signatory>
	<signatory>John Allerton</signatory>
	<signatory>Thomas English</signatory>
	<signatory>Edward Doty</signatory>
	<signatory>Edward Leister</signatory>
	<see-also>
		<link href="index-es.html">Índice</link>
		<link href="document.xsd">Esquema</link>
		<link href="mayflower.xml" lang="en">English</link>
	</see-also>
	<copyright>
		<paragraph>Los contenidos de esta página encuentra en dominio público.</paragraph>
		<paragraph>Los XML y XSLT asociados son ©2020 Benjamin Herman, para uso bajo la <link href="license.txt" lang="en">licencia MIT</link> (disponible en inglés solamente).</paragraph>
	</copyright>
</document>

=== metanomial/constitution/mayflower.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="document.xsl"?>
<document
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="document.xsd"
	heading="The Mayflower Compact"
	lang="en">
	<paragraph><strong>In the name of God, Amen.</strong> We, whose names are underwritten, the Loyal Subjects of our dread Sovereign Lord King James, by the Grace of God, of Great Britain, France, and Ireland, King, Defender of the Faith, &amp;c. Having undertaken for the Glory of God, and Advancement of the Christian Faith, and the Honour of our King and Country, a Voyage to plant the first Colony in the northern Parts of Virginia; Do by these Presents, solemnly and mutually, in the Presence of God and one another, covenant and combine ourselves together into a civil Body Politick, for our better Ordering and Preservation, and Furtherance of the Ends aforesaid: And by Virtue hereof do enact, constitute, and frame, such just and equal Laws, Ordinances, Acts, Constitutions, and Officers, from time to time, as shall be thought most meet and convenient for the general Good of the Colony; unto which we promise all due Submission and Obedience. <strong>In Witness</strong> whereof we have hereunto subscribed our names at Cape-Cod the eleventh of November, in the Reign of our Sovereign Lord King James, of England, France, and Ireland, the eighteenth, and of Scotland the fifty-fourth, Anno Domini; 1620.</paragraph>
	<signatory>John Carver</signatory>
	<signatory>William Bradford</signatory>
	<signatory>Edward Winslow</signatory>
	<signatory>William Brewster</signatory>
	<signatory>Isaac Allerton</signatory>
	<signatory>Captain Myles Standish</signatory>
	<signatory>John Alden</signatory>
	<signatory>Samuel Fuller</signatory>
	<signatory>Christopher Martin</signatory>
	<signatory>William Mullins</signatory>
	<signatory>William White</signatory>
	<signatory>Richard Warren</signatory>
	<signatory>John Howland</signatory>
	<signatory>Stephen Hopkins</signatory>
	<signatory>Edward Tilley</signatory>
	<signatory>John Tilley</signatory>
	<signatory>Francis Cooke</signatory>
	<signatory>Thomas Rogers</signatory>
	<signatory>Thomas Tinker</signatory>
	<signatory>John Rigsdale</signatory>
	<signatory>Edward Fuller</signatory>
	<signatory>John Turner</signatory>
	<signatory>Francis Eaton</signatory>
	<signatory>James Chilton</signatory>
	<signatory>John Crackstone</signatory>
	<signatory>John Billington</signatory>
	<signatory>Moses Fletcher</signatory>
	<signatory>John Goodman</signatory>
	<signatory>Degory Priest</signatory>
	<signatory>Thomas Williams</signatory>
	<signatory>Gilbert Winslow</signatory>
	<signatory>Edmund Margeson</signatory>
	<signatory>Peter Browne</signatory>
	<signatory>Richard Britteridge</signatory>
	<signatory>George Soule</signatory>
	<signatory>Richard Clarke</signatory>
	<signatory>Richard Gardiner</signatory>
	<signatory>John Allerton</signatory>
	<signatory>Thomas English</signatory>
	<signatory>Edward Doty</signatory>
	<signatory>Edward Leister</signatory>
	<see-also>
		<link href="index.html">Index</link>
		<link href="document.xsd">Schema</link>
		<link href="mayflower-es.xml" lang="es">Español</link>
	</see-also>
	<copyright>
		<paragraph>The contents of this page are public domain.</paragraph>
		<paragraph>The associated XML and XSLT are ©2020 Benjamin Herman, for use under the <link href="license.txt">MIT License</link>.</paragraph>
	</copyright>
</document>

=== metanomial/constitution/bill-of-rights-es.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="document.xsl"?>
<document
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="document.xsd"
	heading="Carta de Derechos"
	lang="en">
	<section heading="Preámbulo de la Carta de Derechos">
		<paragraph>El Congreso de los Estados Unidos iniciado y concluido en la Ciudad de Nueva York, el miércoles cuatro de marzo, del año mil setecientos ochenta y nueve.</paragraph>
		<paragraph>Las Convenciones de un número de Estados, habiendo en el momento de adoptar la Constitución, expresado el deseo, con el fin de prevenir el abuso o malinterpretación de sus poderes, de que cláusulas adicionales declaratorias y restrictivas deberían ser añadidas: Y al extender el ámbito de confianza pública hacia el Gobierno, es la mejor forma de asegurar el fin benéfico de su institución.</paragraph>
		<paragraph>Resuelto por el Senado y la Cámara de Representantes de los Estados Unidos, reunidos como Congreso, concurriendo con dos tercios de ambas cámaras, que los siguientes artículos sean propuestos a las asambleas legislativas de los distintos estados, como enmiendas a la Constitución de los Estados Unidos, con todos, o algunos de estos artículos, cuando sean ratificados por tres cuartos de dichas asambleas legislativas, sean válidos para todos los fines y propósitos, como parte de la Constitución; viz.</paragraph>
		<paragraph>Los Artículo añadidos, y enmiendas a la Constitución de los Estados Unidos de América, propuestos por el Congreso, y ratificados por las asambleas legislativas de varios estados, de acuerdo con lo dispuesto en el quinto artículo de la Constitución original.</paragraph>
	</section>
	<section heading="Enmienda I">
		<paragraph>El Congreso no aprobará ley alguna por la que adopte una religión oficial del estado o prohíba el libre ejercicio de la misma, o que restrinja la libertad de expresión o de prensa, o el derecho del pueblo a reunirse pacíficamente y a pedir al gobierno la reparación de agravios.</paragraph>
	</section>
	<section heading="Enmienda II">
		<paragraph>Siendo necesaria una milicia bien ordenada para la seguridad de un estado libre, no se violará el derecho del pueblo a poseer y portar armas.</paragraph>
	</section>
	<section heading="Enmienda III">
		<paragraph>En tiempo de paz no se alojará a ningún soldado en casa alguna sin el consentimiento del propietario; ni en tiempo de guerra, excepto en la forma prescrita por ley.</paragraph>
	</section>
	<section heading="Enmienda IV">
		<paragraph>El derecho del pueblo a que sus personas, domicilios, papeles y efectos se encuentren protegidos contra registros e incautaciones irrazonables, será inviolable, y no se expedirán al efecto órdenes que no se apoyen en un motivo verosímil, estén corroborados mediante juramento o afirmación y describan con particularidad el lugar que deba ser registrado y las personas o cosas que han de ser incautadas.</paragraph>
	</section>
	<section heading="Enmienda V">
		<paragraph>Nadie estará obligado a responder de un delito castigado con la pena capital o de otro delito infame a menos que un gran jurado lo acuse, a excepción de los casos que se presenten en las fuerzas navales o terrestres, o en la milicia nacional cuando se encuentre en servicio actual en tiempo de guerra o peligro público; tampoco se juzgará a persona alguna dos veces con motivo del mismo delito, el cual conlleve la pérdida de la vida o algún miembro; ni se le compelerá a declarar contra sí misma en ningún juicio criminal; ni se le privará de la vida, la libertad o la propiedad sin el debido proceso legal; ni se tomará propiedad privada para uso público sin una justa indemnización.</paragraph>
	</section>
	<section heading="Enmienda VI">
		<paragraph>En toda causa criminal, el acusado gozará del derecho de ser juzgado rápidamente y en público por un jurado imparcial del distrito y estado en que el delito se haya cometido, Distrito que deberá haber sido determinado previamente por ley; así como de que se le haga saber la naturaleza y causa de la acusación, de que se caree con los testigos en su contra, de que se obligue a comparecer a los testigos que le favorezcan y de contar con la ayuda de un abogado que le defienda.</paragraph>
	</section>
	<section heading="Enmienda VII">
		<paragraph>El derecho a que se celebren ante un jurado los juicios de derecho consuetudinario en que el valor en disputa exceda de veinte dólares, será garantizado, y ningún hecho juzgado por un jurado será reexaminado en tribunal alguno de los Estados Unidos, salvo con arreglo a las normas del derecho consuetudinario.</paragraph>
	</section>
	<section heading="Enmienda VIII">
		<paragraph>No se exigirán fianzas excesivas, ni se impondrán multas excesivas, ni se infligirán penas crueles e inusuales.</paragraph>
	</section>
	<section heading="Enmienda IX">
		<paragraph>No se interpretará la enumeración en la Constitución de ciertos derechos para negar o menospreciar otros derechos retenidos por el pueblo.</paragraph>
	</section>
	<section heading="Enmienda X">
		<paragraph>Los poderes que la Constitución no delega a los Estados Unidos ni prohíbe a los Estados, quedan reservados a los estados respectivamente o al pueblo.</paragraph>
	</section>
	<see-also>
		<link href="index-es.html">Índice</link>
		<link href="document.xsd">Esquema</link>
		<link href="bill-of-rights.xml" lang="en">English</link>
	</see-also>
	<copyright>
		<paragraph>Los contenidos de esta página encuentra en dominio público.</paragraph>
		<paragraph>Los XML y XSLT asociados son ©2020 Benjamin Herman, para uso bajo la <link href="license.txt" lang="en">licencia MIT</link> (disponible en inglés solamente).</paragraph>
	</copyright>
</document>
